version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: gamenotebook_mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gamenotebook_db
      MYSQL_USER: user
      MYSQL_PASSWORD: f50bd140
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./server
    container_name: gamenotebook_nestjs_server
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_HOST: mysql
      DATABASE_PORT: 3306
      DATABASE_USER: user
      DATABASE_PASSWORD: f50bd140
      DATABASE_NAME: gamenotebook_db
    ports:
      - "3000:3000"
    volumes:
      - ./server:/app
    command: npm run start:dev

volumes:
  mysql_data:
